apiVersion: apps/v1
kind: Deployment
metadata:
  name: me
  namespace: me
spec:
  selector:
    matchLabels:
      app: me
  template:
    metadata:
      labels:
        app: me
    spec:
      containers:
      - name: me
        image: ghcr.io/aksharpatel47/me:main-6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
