name: Deploy
on:
  repository_dispatch:
    types: [image_push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update image tag in deployment
        run: |
          sed -i "s|${{ github.event.client_payload.IMAGE_NAME }}:.*|${{ github.event.client_payload.IMAGE_NAME }}:${{ github.event.client_payload.IMAGE_TAG }}|g" ${{ github.event.client_payload.CHART_PATH }}
      - name: Commit and push changes
        run: |
          git config --global user.email akshar.patel.47@gmail.com
          git config --global user.name aksharpatel47
          git add ${{ github.event.client_payload.CHART_PATH }}
          git commit -m "Update image tag for ${{ github.event.client_payload.CHART_PATH }} to ${{ github.event.client_payload.IMAGE_TAG }}"
          git push origin main
          
